### ISSUE TITLE
sqlite sessions crossing thread boundaries

### ISSUE THREAD

**Issue by alexjurkiewicz** [Kramin42/Crawl-Log-Api#5]
Seeing this in the logfile:

```
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 139645714892544 and this is thread id 139645586687744
ERROR:sqlalchemy.pool.NullPool:Exception closing connection <sqlite3.Connection object at 0x7f01c4f509d0>
Traceback (most recent call last):
  File "/app/pubsub/venv/lib/python3.5/site-packages/sqlalchemy/pool.py", line 687, in _finalize_fairy
    fairy._reset(pool)
  File "/app/pubsub/venv/lib/python3.5/site-packages/sqlalchemy/pool.py", line 829, in _reset
    pool._dialect.do_rollback(self)
  File "/app/pubsub/venv/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 439, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 139645714892544 and this is thread id 139645586687744

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/pubsub/venv/lib/python3.5/site-packages/sqlalchemy/pool.py", line 300, in _close_connection
    self._dialect.do_close(connection)
  File "/app/pubsub/venv/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 445, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 139645714892544 and this is thread id 139645586687744```

I think if you're using threads you need a new session in each thread.

**Comment by Kramin42** [comment]
hopefully fixed by d928638409f880e7851b701b9bef0e8dd0468897
